### ISSUE TITLE
Закрытие вкладки не удаляет игрока.

### ISSUE THREAD

**Issue by nochgame** [nochgames/client#11]
При закрытии вкладки с активным игроком, он пропадает на сервере, но отрисовка на клиенте сохраняется. 
Причем, так как реального "тела" у оставшегося атома нет, он никак не взаимодействует ни с чем, а лишь выполняет роль картинки поверх всего.  
![default](https://cloud.githubusercontent.com/assets/17674608/13615474/8a44057e-e586-11e5-8a9d-af08741fa030.png)

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Now closing the tab does delete atoms but.. 
what about the rubish on it's place instead?
 It just disappeares now.
But it turns into rubish when was absorbed at least :+1:

**Comment by DmitryTsyganov** [comment]
It happens because same functions are called on socket close and when player collides with border. 
see server issue 15
no client bugs, so
closed.
