### ISSUE TITLE
Игроки видят друг друга в неверных местах.

### ISSUE THREAD

**Issue by nochgame** [nochgames/client#12]
Атомы игроков отображаются не так, как есть на самом деле. Причем, срабатывает "поглощение" корректно и действительное их положение также корректно относительно друг друга и мусора вокруг, но отрисовка атома соперника и его мусора происходит некорректно. 
Все на видео ниже.
https://vk.com/video?z=video55041164_456239038%2Ff5fb90ba56f96d68cd%2Fpl_updates

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Fixed.
