### ISSUE TITLE
Фон застревает в левом верхнем углу экрана

### ISSUE THREAD

**Issue by ericovva** [nochgames/client#6]
Снимка нет, но тут очевидос

**Comment by DmitryTsyganov** [comment]
Оптимизация с жёстким откидыванием дробной части оператором << не даёт медленным элементам пройти через 0.

**Comment by DmitryTsyganov** [comment]
Оптимизция временно отключена.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Молекулы заднего фона появляются всюду, но после ввода логина и приближении экрана, все, что вне видимости, просто исчезают. Однако, облака рождаются и расползаются равномерно по всей карте. С учетом того, что мы собираемся заменить эти фоновые молекулы на рандомный вылет мелких частиц поверх экрана, я не вижу особого 
смысла исправлять этот баг.

![1](https://cloud.githubusercontent.com/assets/17674608/13607073/a0d312de-e55f-11e5-8241-39316d716f93.png)
![default](https://cloud.githubusercontent.com/assets/17674608/13607079/a50de888-e55f-11e5-8423-e69ba62ecef2.png)
![3](https://cloud.githubusercontent.com/assets/17674608/13607084/a71bb6a0-e55f-11e5-8470-518edd8adecf.png)
