### ISSUE TITLE
Резкое появление мусора.

### ISSUE THREAD

**Issue by nochgame** [nochgames/client#8]
При движении, некоторые атомы мусора постепенно выходят из-за края экрана, также постепенно заходят за край экрана. Так и должно быть. Но некоторые атомы появляются и исчезают мгновенно и целиком, не заходя за край экрана даже частично. Это не зависит от типа атома или скорости движения. То есть, частота отрисовки тут ни при чем.
![1](https://cloud.githubusercontent.com/assets/17674608/13551239/1bc1aa32-e344-11e5-9d33-7486d2338317.png)
![2](https://cloud.githubusercontent.com/assets/17674608/13551241/1e0de8b4-e344-11e5-89c4-f91dadfa3b79.png)

**Comment by DmitryTsyganov** [comment]
Перенести в сервер
