### ISSUE TITLE
Произвольное изменение толщины обводки атома игрока.

### ISSUE THREAD

**Issue by nochgame** [nochgames/client#9]
Толщина обводки атома игрока меняется на рандоме. 
![1](https://cloud.githubusercontent.com/assets/17674608/13551288/68b70c00-e345-11e5-97ae-b4fc7be4e6a5.png)
![2](https://cloud.githubusercontent.com/assets/17674608/13551289/69799e32-e345-11e5-8aa9-a1ce1dc37a00.png)
![3](https://cloud.githubusercontent.com/assets/17674608/13551295/88b1c2c0-e345-11e5-965f-7136e5083cde.png)

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by nochgame** [comment]
Более не меняется толщина обводки атома игрока любого вида. Ни в молекуле, ни при удалении экрана. Issue is closed.
